-- Never discard a persisted preparation or its audit during downgrade.
DO $$ BEGIN IF EXISTS(SELECT 1 FROM vpn_credential_revocations) THEN RAISE EXCEPTION 'revocation history requires explicit archival before downgrade'; END IF; END; $$;
DROP TRIGGER rg141_manager_update ON update_jobs;
DROP TRIGGER rg141_rule_sets ON managed_routing_rule_sets;
DROP TRIGGER rg141_routing ON routing_profiles;
DROP TRIGGER rg141_server_routing ON server_routing_profiles;
DROP TRIGGER rg141_rules ON routing_profile_rules;
DROP TRIGGER rg141_version ON config_versions;
DROP TRIGGER rg141_agent ON agents;
DROP TRIGGER rg141_server ON servers;
DROP TRIGGER rg141_traffic_limit ON traffic_limits;
DROP TRIGGER rg141_account_selection ON vpn_account_automatic_selection_policies;
DROP TRIGGER rg141_account_groups ON vpn_account_node_groups;
DROP TRIGGER rg141_account_routing ON vpn_account_routing_profiles;
DROP TRIGGER rg141_protocols ON vpn_account_protocols;
DROP TRIGGER rg141_profile ON vpn_client_profiles;
DROP TRIGGER rg141_account ON vpn_accounts;
DROP TRIGGER rg141_transfer_node ON vpn_account_transfer_nodes;
DROP TRIGGER rg141_update_job ON agent_platform_update_jobs;
DROP TRIGGER rg141_operation_job ON agent_operation_jobs;
DROP TRIGGER rg141_config_job ON config_apply_jobs;
DROP TRIGGER rg141_audit_immutable ON vpn_credential_revocation_events;
DROP TRIGGER rg141_audit ON vpn_credential_revocations;
DROP TRIGGER rg141_ledger ON vpn_credential_revocations;
DROP FUNCTION routegate_revocation_manager_update_guard();
DROP FUNCTION routegate_revocation_routing_guard();
DROP FUNCTION routegate_revocation_version_guard();
DROP FUNCTION routegate_revocation_agent_guard();
DROP FUNCTION routegate_revocation_server_guard();
DROP FUNCTION routegate_revocation_preferences_guard();
DROP FUNCTION routegate_revocation_account_guard();
DROP FUNCTION routegate_revocation_job_guard();
DROP FUNCTION routegate_revocation_node_guard(uuid);
DROP FUNCTION routegate_revocation_audit_guard();
DROP FUNCTION routegate_revocation_audit();
DROP FUNCTION routegate_revocation_ledger_guard();
DROP TABLE vpn_credential_revocation_events;
DROP TABLE vpn_credential_revocations;
