DROP TRIGGER rg140_manager_update ON update_jobs;
DROP FUNCTION routegate_transfer_manager_update_guard();
DROP TRIGGER z_rg140_cutover_timestamp ON vpn_accounts;
DROP FUNCTION routegate_transfer_cutover_timestamp();
DROP TRIGGER rg140_routing_profiles ON routing_profiles;
DROP TRIGGER rg140_server_routing ON server_routing_profiles;
DROP TRIGGER rg140_routing_rules ON routing_profile_rules;
DROP FUNCTION routegate_transfer_shared_routing_guard();
DROP TRIGGER rg140_job_proof ON config_apply_jobs;
DROP TRIGGER rg140_version_proof ON config_versions;
DROP FUNCTION routegate_transfer_proof_guard();
DROP TRIGGER IF EXISTS rg140_server ON servers;
DROP TRIGGER IF EXISTS rg140_routing ON vpn_account_routing_profiles;
DROP TRIGGER IF EXISTS rg140_protocols ON vpn_account_protocols;
DROP TRIGGER IF EXISTS rg140_profile ON vpn_client_profiles;
DROP TRIGGER IF EXISTS rg140_account ON vpn_accounts;
DROP TRIGGER IF EXISTS rg140_update_job ON agent_platform_update_jobs;
DROP TRIGGER IF EXISTS rg140_operation_job ON agent_operation_jobs;
DROP TRIGGER IF EXISTS rg140_config_job ON config_apply_jobs;
DROP FUNCTION routegate_transfer_server_guard();
DROP FUNCTION routegate_transfer_preferences_guard();
DROP FUNCTION routegate_transfer_account_guard();
DROP FUNCTION routegate_transfer_job_guard();
DROP FUNCTION routegate_transfer_node_guard(uuid);
DROP TABLE vpn_account_transfer_nodes;
DROP TABLE vpn_account_transfers;
