import { getCurrentLocale } from '../../shared/i18n/i18n';

export function getVpnAccountManagementCopy() {
  if (getCurrentLocale() === 'ru') {
    return {
      pageSubtitle: 'Управляйте VPN-аккаунтами, протоколами подключения, доступом, маршрутами и лимитами трафика.',
      searchPlaceholder: 'Поиск по имени, email, заметкам, ID или VLESS UUID…',
      search: 'Найти',
      clear: 'Сбросить',
      allStatuses: 'Все статусы',
      allServers: 'Все серверы',
      shown: (from: number, to: number, total: number) => `Показано ${from}–${to} из ${total}`,
      page: (page: number, total: number) => `Страница ${page} из ${Math.max(total, 1)}`,
      previous: '← Назад',
      next: 'Вперёд →',
      perPage: 'На странице',
      selected: (count: number) => `Выбрано: ${count}`,
      selectPage: 'Выбрать страницу',
      selectAllMatching: (count: number) => `Выбрать все ${count} найденных`,
      allMatchingSelected: (count: number) => `Выбраны все ${count} найденных аккаунтов`,
      clearSelection: 'Снять выбор',
      activate: 'Активировать',
      suspend: 'Приостановить',
      revoke: 'Отозвать',
      delete: 'Удалить',
      assignServer: 'Перенести на сервер',
      applyAssignment: 'Назначить',
      bulkWorking: 'Выполняем…',
      bulkConfirmDelete: (count: number) => `Безвозвратно удалить ${count} VPN-аккаунт(ов)?\n\nЭто действие нельзя отменить.`,
      bulkConfirmRevoke: (count: number) => `Отозвать доступ у ${count} VPN-аккаунт(ов)?`,
      bulkDone: (count: number) => `Операция выполнена для ${count} VPN-аккаунт(ов).`,
      bulkError: 'Не удалось выполнить массовую операцию для всех выбранных аккаунтов.',
      noMatchesTitle: 'VPN-аккаунты не найдены',
      noMatchesDescription: 'Измените поисковый запрос или фильтры.',
      filtersLabel: 'Фильтры VPN-аккаунтов',
      actions: 'Действия',
      identityTitle: 'Данные аккаунта',
      identitySubtitle: 'Имя, контакты и внутренние заметки администратора.',
      lifecycleTitle: 'Состояние аккаунта',
      lifecycleSubtitle: 'Активируйте или приостановите аккаунт либо отзовите доступ к нему.',
      dangerSubtitle: 'Удаление аккаунта необратимо.',
      accountName: 'Имя аккаунта',
      accountNamePlaceholder: 'Например: Иван Петров, iPhone, Офис Москва',
      accountNameHint: 'Имя человека, устройства или назначения VPN-аккаунта.',
      save: 'Сохранить изменения',
      saving: 'Сохраняем…',
      editSuccess: 'VPN-аккаунт обновлён.',
      editError: 'Не удалось обновить VPN-аккаунт.',
      loadAccountError: 'Не удалось загрузить выбранный VPN-аккаунт.',
      notes: 'Заметки',
      notesPlaceholder: 'Например: ноутбук директора, временный подрядчик, офис Москва…',
      notesHint: 'Внутренняя заметка администратора. Не попадает в VPN-профиль, QR-код или подписку.',
      notesLoadError: 'Не удалось загрузить заметки аккаунта.',
      maxDevices: 'Максимум устройств',
      unlimited: 'Без ограничения',
      expiration: 'Срок действия',
      noExpiration: 'Без срока действия',
      dangerZone: 'Опасная зона',
      revokeConfirm: (name: string) => `Отозвать доступ у VPN-аккаунта «${name}»?`,
      deleteAccount: 'Удалить аккаунт безвозвратно',
      deleteConfirm: (name: string) => `Безвозвратно удалить VPN-аккаунт «${name}»?\n\nЭто действие нельзя отменить.`,
      deleteSuccess: 'VPN-аккаунт удалён.',
      deleteError: 'Не удалось удалить VPN-аккаунт.',
      statusCreated: 'Создан',
      statusActive: 'Активен',
      statusSuspended: 'Приостановлен',
      statusExpired: 'Истёк',
      statusRevoked: 'Отозван',
      configNotice: 'Изменения затронули конфигурацию VPN-сервера и требуют нового развёртывания.',
      unassignedConfigNotice: 'Аккаунт не назначен серверу; изменения доступа не требуют развёртывания конфигурации.',
      openDeploy: 'Открыть развёртывание конфигов →',
    } as const;
  }

  return {
    pageSubtitle: 'Manage VPN accounts, connection protocols, access delivery, routing, and traffic limits.',
    searchPlaceholder: 'Search by account name, email, notes, ID, or VLESS UUID…',
    search: 'Search',
    clear: 'Reset',
    allStatuses: 'All statuses',
    allServers: 'All servers',
    shown: (from: number, to: number, total: number) => `Showing ${from}–${to} of ${total}`,
    page: (page: number, total: number) => `Page ${page} of ${Math.max(total, 1)}`,
    previous: '← Previous',
    next: 'Next →',
    perPage: 'Per page',
    selected: (count: number) => `Selected: ${count}`,
    selectPage: 'Select page',
    selectAllMatching: (count: number) => `Select all ${count} matching`,
    allMatchingSelected: (count: number) => `All ${count} matching accounts selected`,
    clearSelection: 'Clear selection',
    activate: 'Activate',
    suspend: 'Suspend',
    revoke: 'Revoke',
    delete: 'Delete',
    assignServer: 'Move to server',
    applyAssignment: 'Assign',
    bulkWorking: 'Working…',
    bulkConfirmDelete: (count: number) => `Permanently delete ${count} VPN account(s)?\n\nThis cannot be undone.`,
    bulkConfirmRevoke: (count: number) => `Revoke access for ${count} VPN account(s)?`,
    bulkDone: (count: number) => `Operation completed for ${count} VPN account(s).`,
    bulkError: 'The bulk operation could not be completed for every selected account.',
    noMatchesTitle: 'No VPN accounts found',
    noMatchesDescription: 'Change the search query or filters.',
    filtersLabel: 'VPN account filters',
    actions: 'Actions',
    identityTitle: 'Account details',
    identitySubtitle: 'Name, contact details, and internal administrator notes.',
    lifecycleTitle: 'Account state',
    lifecycleSubtitle: 'Activate or suspend this account, or revoke its access.',
    dangerSubtitle: 'Deleting this account cannot be undone.',
    accountName: 'Account name',
    accountNamePlaceholder: 'For example: John Smith, iPhone, Moscow office',
    accountNameHint: 'A person, device, or purpose represented by this VPN account.',
    save: 'Save changes',
    saving: 'Saving…',
    editSuccess: 'VPN account updated.',
    editError: 'Failed to update VPN account.',
    loadAccountError: 'Failed to load the selected VPN account.',
    notes: 'Notes',
    notesPlaceholder: 'For example: director laptop, temporary contractor, Moscow office…',
    notesHint: 'Internal administrator note. It is never included in VPN profiles, QR codes, or subscriptions.',
    notesLoadError: 'Failed to load account notes.',
    maxDevices: 'Maximum devices',
    unlimited: 'Unlimited',
    expiration: 'Expiration',
    noExpiration: 'No expiration',
    dangerZone: 'Danger zone',
    revokeConfirm: (name: string) => `Revoke access for VPN account “${name}”?`,
    deleteAccount: 'Delete account permanently',
    deleteConfirm: (name: string) => `Permanently delete VPN account “${name}”?\n\nThis cannot be undone.`,
    deleteSuccess: 'VPN account deleted.',
    deleteError: 'Failed to delete VPN account.',
    statusCreated: 'Created',
    statusActive: 'Active',
    statusSuspended: 'Suspended',
    statusExpired: 'Expired',
    statusRevoked: 'Revoked',
    configNotice: 'The changes affected a VPN server configuration and require a new deployment.',
    unassignedConfigNotice: 'This account is not assigned to a server; access changes do not require a configuration deployment.',
    openDeploy: 'Open Config Deploy →',
  } as const;
}
